"use client";
import * as React from "react";
import { StakingCard } from "./StakingCard";
import { ProgramTitle } from "./ProgramTitle";

export const StakingProgramSection: React.FC = () => {
  return (
    <section className="max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col  items-center " >
        <div className="w-[37%] max-md:ml-0 max-md:w-full  rounded-3xl">
          <StakingCard
            imageUrl="/staking1.png"
            text="Interest from secured agricultural loans"
          />
        </div>
        <ProgramTitle title="Staking Program" colorClass="text-yellow-400" />
        <div className="ml-5 w-[37%] max-md:ml-0 max-md:w-full  rounded-3xl">
          <StakingCard
            imageUrl="/staking2.png"
            text="Profits generated by successful farming projects"
          />
        </div>
      </div>
    </section>
  );
};
